name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed packages/koni_jxl packages/koni_jxl_flutter
      - run: dart analyze --fatal-infos
      - run: dart test
        working-directory: packages/koni_jxl
      - run: flutter test
        working-directory: packages/koni_jxl_flutter
      - run: flutter test
        working-directory: packages/koni_jxl_flutter/example
